###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "2"

volumes:
  mariadb-data:

services:
    mariadb:
      build:
        context: .
        dockerfile: Dockerfile.mariadb
      container_name: honestybar-mariadb
      working_dir: /application
      volumes:
        - mariadb-data:/config/databases
      #volumes:
      #  - ./mariadb-data:/config/databases
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=honesty
        - MYSQL_USER=oli
        - MYSQL_PASSWORD=password
      ports:
        - "7072:3306"

    webserver:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      container_name: honestybar-webserver
      working_dir: /application
      ports:
       - "7070:80"

    wpe:
      restart: always
      build:
        context: ./
        dockerfile: Dockerfile.wpe
      privileged: true
      ports:
        - "8080:8080"

    php-fpm:
      build:
        context: .
        dockerfile: Dockerfile.php-fpm
      container_name: honestybar-php-fpm
      working_dir: /application

