version: "2.1"

volumes:
  mariadb-data:

services:
  
  alpine-nginx-php-container:
    build:
      context: alpine-nginx-php
      dockerfile: hello
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Europe/London"
      PHP_ERRORS: 1
      PHP_POST_MAX_SIZE: 250
      PHP_UPLOAD_MAX_FILESIZE: 250

  wpe:
    restart: always
    build:
      context: alpine-nginx-php
      dockerfile: ./Dockerfile.wpe
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - alpine-nginx-php-container

  honestybar-mariadb:
    build:
      context: alpine-nginx-php
      dockerfile: ./Dockerfile.mariadb
    container_name: honestybar-mariadb
    working_dir: /application
    volumes:
      - mariadb-data:/config/databases
    #volumes:
    #  - ./mariadb-data:/config/databases
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=honesty
      - MYSQL_USER=oli
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    ports:
      - "7072:3306"
