FROM arm32v7/php
#FROM phpdockerio/php74-fpm:latest
WORKDIR "/application"

COPY . /application
COPY ./phpdocker/php-fpm/php-ini-overrides.ini /etc/php/7.4/fpm/conf.d/99-overrides.ini

#RUN apt-get update \
#    && apt-get install php7.4-mysql \
#    && apt-get install nano

EXPOSE 9000
